let status = {
    RECEIVED: 'RECEIVED',
    ESTIMATE_SUBMITTED: 'ESTIMATE SUBMITTED',
    ESTIMATE_APPROVED: 'ESTIMATE APPROVED',
    IN_REPAIR: 'IN REPAIR',
    IN_FACTORY: 'IN FACTORY',
    REPAIRED: 'REPAIRED',
    DELIVERED: 'DELIVERED',
    CANCELED: 'CANCELED',
}

module.exports = status;